spring:
  application:
    name: LoL Statikk
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/lolstatikk
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false